### ISSUE TITLE
Missing file used in gensup_analysis.R

### ISSUE THREAD

**Issue by Jeremy37** [ericminikel/genetic_support#2]
A line in gensup_analysis.R attempts to read in the file:
`../digap/data/gwascat/gwas_catalog-ancestry_r2022-02-02.tsv`

I couldn't find this file anywhere in the github repository. Can it be provided? Or alternatively, can this analysis be left out so that the script can complete successfully?

(By the way, kudos on providing such a complete and easy to run repository for reproducing your paper's analyses.)

**Comment by ericminikel** [comment]
D'oh, sorry about that! Fixed now on main branch with commit b84cf0580b7df1af14b2c72068ed42b5aa0c52a4 , please try again. Thank for your kind words!

**Comment by ericminikel** [comment]
Closing this then, let me know if you spot anything else
