### ISSUE TITLE
merge2.tsv produced by genetic associations with l2g_share >= 0.1

### ISSUE THREAD

**Issue by rogierhintzen** [ericminikel/genetic_support#3]
I think [merge2.tsv.gz](https://github.com/ericminikel/genetic_support/blob/main/data/merge2.tsv.gz) is derived from the set of genetic associations with l2g_share >= 0.1, rather than 0.5 as per the main results in the paper. This may have been leftover from the parameter sweep across l2g_share from Fig 1C.

You can derive the appropriate dataframe from [assoc.tsv.gz](https://github.com/ericminikel/genetic_support/blob/main/data/assoc.tsv.gz) but it would be much appreciated having the dataframe that produces the main results in the repo.

**Comment by ericminikel** [comment]
This is intended; this TSV file is supposed to support all analyses in the paper including the parameter sweep that you mention. 

The majority of analyses in the paper use `combined_ti` which is set here: https://github.com/ericminikel/genetic_support/blob/b84cf0580b7df1af14b2c72068ed42b5aa0c52a4/src/gensup_analysis.R#L799

Table S01 is also a useful starting point if you just need to browse things https://github.com/ericminikel/genetic_support/blob/main/display_items/table_s01.tsv
